### ISSUE TITLE
Make input shape variable

### ISSUE THREAD

**Issue by harumattya** [bonlime/keras-deeplab-v3-plus#65] opened 2019-01-10 09:11 UTC
Hello, thank you for your great work. It is very helpful!

I would like to make `input_shape` variable like `model = Deeplabv3(input_shape=(None, None, channels))`  .
However, it doesn't work because the information is used to calculate `pool_size` or `output_size`  in `model.py` .

Is it possible to modify the source code not to use `input_shape` explicitly?

**Comment by wave-transmitter** [comment] 2019-03-06 09:48
Hello, I am trying to do more or less the same. As far as I understand current model can make predictions on a fixed input image size, as defined during training process.

@bonlime Is that correct? Is it possible to expand the model to predict on variable size input images? I thought that by defining a (None, None, 3) tensor for "input_tensor" argument would solve the problem, but this is not the case.

**Comment by bonlime** [comment] 2019-03-17 21:00
Hi  @wave-transmitter it is probably possible! There is a GlobalAveragePooling2d layer which will do the job, you only need to somehow reshape the result after it to preserve the dimensions. but the upsampling with None is tricky. I'll try to migrate this code to TF Keras soon, maybe then it would be possible to have None as input shapes

**Comment by bonlime** [comment] 2019-03-19 21:42
Added support to `(None, None, ...)` shape  in https://github.com/bonlime/keras-deeplab-v3-plus/commit/64bc7a86422c3ff27c4c7e96c1a640d1ec4eb438

**Closed by bonlime** 2019-03-19 21:42 UTC

**Comment by pluniak** [comment] 2019-05-07 11:11
@bonlime 
I still can't load the model with input_shape=(None, None, 3) using the latest version of your repo:

`Deeplabv3(weights='pascal_voc', input_shape=(None, None, 3), classes=1, backbone='xception', OS=16)` gives me 

`ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, None)` 

caused by lines 417-419 in model.py. I can load the model when replacing x.shape with tf.shape(x) in line 418, but then I'm getting another shape error during training (model.fit). What am I doing wrong? I tried to solve the issue on my own, but it seems to be beyond my skills.


Additional info: using input_shape of 248*248*3 causes 

`ValueError: A `Concatenate` layer requires inputs with matching shapes except for the concat axis. Got inputs shapes: [(None, 64, 64, 256), (None, 62, 62, 48)]` 

in Line 425 in model.py. The TF1.13-based version of this repo accepts 248*248 input images.

Cheers,
Philipp
